[2016-08-14 15:13:33,980] DEBUG    PluginManager Loading plugin: CryptMessage
[2016-08-14 15:13:33,996] DEBUG    - opensslVerify loaded: <CDLL 'libssl.so.1.0.0', handle 176d7d0 at 7fc82c1171d0>
[2016-08-14 15:13:33,997] INFO     - OpenSSL loaded, version: 01000106F
[2016-08-14 15:13:33,997] DEBUG    PluginManager New plugin registered to: UiWebsocket
[2016-08-14 15:13:33,997] DEBUG    PluginManager New plugin registered to: User
[2016-08-14 15:13:33,997] DEBUG    PluginManager Loading plugin: Zeroname
[2016-08-14 15:13:33,998] DEBUG    PluginManager New plugin registered to: UiRequest
[2016-08-14 15:13:33,998] DEBUG    PluginManager New plugin registered to: ConfigPlugin
[2016-08-14 15:13:33,999] DEBUG    PluginManager New plugin registered to: SiteManager
[2016-08-14 15:13:33,999] DEBUG    PluginManager Loading plugin: AnnounceZero
[2016-08-14 15:13:34,000] DEBUG    PluginManager New plugin registered to: Site
[2016-08-14 15:13:34,001] DEBUG    PluginManager Loading plugin: Stats
[2016-08-14 15:13:34,002] DEBUG    PluginManager New plugin registered to: UiRequest
[2016-08-14 15:13:34,002] DEBUG    PluginManager Loading plugin: Newsfeed
[2016-08-14 15:13:34,003] DEBUG    PluginManager New plugin registered to: UiWebsocket
[2016-08-14 15:13:34,003] DEBUG    PluginManager New plugin registered to: User
[2016-08-14 15:13:34,003] DEBUG    PluginManager Loading plugin: Trayicon
[2016-08-14 15:13:34,004] DEBUG    PluginManager Loading plugin: Sidebar
[2016-08-14 15:13:34,005] DEBUG    PluginManager New plugin registered to: UiRequest
[2016-08-14 15:13:34,005] DEBUG    PluginManager New plugin registered to: UiWebsocket
[2016-08-14 15:13:34,005] DEBUG    PluginManager New class accepts plugins: ConfigPlugin (Loaded plugins: [<class 'Zeroname.UiRequestPlugin.ConfigPlugin'>, <class 'Config.ConfigPlugin'>])
[2016-08-14 15:13:34,006] DEBUG    - Config: Config(action='main', batch=False, bit_resolver='1CQTfYmebR1bP75PCUata417NffWyL6AXf', coffeescript_compiler=None, config_file='phantom.conf', connected_limit=15, data_dir='data', debug=False, debug_gevent=False, debug_socket=False, disable_db=False, disable_encryption=False, disable_sslcompression=True, disable_udp=False, fileserver_ip='*', fileserver_port=15441, homepage='1CQTfYmebR1bP75PCUata417NffWyL6AXf', ip_external=None, keep_ssl_cert=False, log_dir='log', max_files_opened=2048, msgpack_purepython=True, open_browser=None, proxy=None, size_limit=10, stream_downloads=False, tor='disable', tor_controller='127.0.0.1:9051', tor_proxy='127.0.0.1:9050', trackers=['zero://boot3rdez4rzn36x.onion:15441', 'zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441', 'udp://tracker.coppersurfer.tk:6969', 'udp://tracker.leechers-paradise.org:6969', 'udp://9.rarbg.com:2710', 'http://tracker.aletorrenty.pl:2710/announce', 'http://explodie.org:6969/announce', 'http://torrent.gresille.org/announce'], trackers_file=False, ui_ip='127.0.0.1', ui_port=53903, ui_restrict=False, use_openssl=True, use_tempfiles=False, verbose=False)
[2016-08-14 15:13:34,006] INFO     - Version: 0.1a r1098, Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2], Gevent: 1.1.1
[2016-08-14 15:13:34,012] DEBUG    PluginManager New class accepts plugins: SiteManager (Loaded plugins: [<class 'Zeroname.SiteManagerPlugin.SiteManagerPlugin'>, <class 'Site.SiteManager.SiteManager'>])
[2016-08-14 15:13:34,012] DEBUG    PluginManager New class accepts plugins: Site (Loaded plugins: [<class 'AnnounceZero.AnnounceZeroPlugin.SitePlugin'>, <class 'Site.Site.Site'>])
[2016-08-14 15:13:34,018] DEBUG    - Disabled SSL compression on <CDLL 'libssl.so.1.0.0', handle 176d7d0 at 7fc82bff3390>
[2016-08-14 15:13:34,018] DEBUG    - Python SSL version: OpenSSL 1.0.1f 6 Jan 2014
[2016-08-14 15:13:34,029] DEBUG    PluginManager New class accepts plugins: User (Loaded plugins: [<class 'Newsfeed.NewsfeedPlugin.UserPlugin'>, <class 'CryptMessage.CryptMessagePlugin.UserPlugin'>, <class 'User.User.User'>])
[2016-08-14 15:13:34,030] DEBUG    PluginManager New class accepts plugins: UiWebsocket (Loaded plugins: [<class 'Sidebar.SidebarPlugin.UiWebsocketPlugin'>, <class 'Newsfeed.NewsfeedPlugin.UiWebsocketPlugin'>, <class 'CryptMessage.CryptMessagePlugin.UiWebsocketPlugin'>, <class 'Ui.UiWebsocket.UiWebsocket'>])
[2016-08-14 15:13:34,030] DEBUG    PluginManager New class accepts plugins: UiRequest (Loaded plugins: [<class 'Sidebar.SidebarPlugin.UiRequestPlugin'>, <class 'Stats.StatsPlugin.UiRequestPlugin'>, <class 'Zeroname.UiRequestPlugin.UiRequestPlugin'>, <class 'Ui.UiRequest.UiRequest'>])
[2016-08-14 15:13:34,031] INFO     - Creating FileServer....
[2016-08-14 15:13:34,031] INFO     - Creating UiServer....
[2016-08-14 15:13:34,031] DEBUG    - Loading sites...
[2016-08-14 15:13:34,033] DEBUG    - Loaded site 1Pz5E5vnZy5jSqLSQhuNyeK9QxpHGrxGKG in 0.002s
[2016-08-14 15:13:34,035] DEBUG    - Loaded site 1CQTfYmebR1bP75PCUata417NffWyL6AXf in 0.001s
[2016-08-14 15:13:34,035] DEBUG    - SiteManager added 2 sites
[2016-08-14 15:13:34,035] INFO     gshift Starting gshift...
[2016-08-14 15:13:34,046] INFO     - Removing old SSL certs...
[2016-08-14 15:13:34,047] INFO     - - Starting servers....
[2016-08-14 15:13:34,107] DEBUG    - Generating RSA cert and key PEM files...Generating a 2048 bit RSA private key
.............+++
.......+++
unable to write 'random state'
writing new private key to 'data/key-rsa.pem'
-----
[2016-08-14 15:13:34,108] DEBUG    FileServer Binding to: *:15441, (msgpack: 0.4.6), supported crypt: ['tls-rsa']
[2016-08-14 15:13:34,108] DEBUG    FileServer Checking sites...
[2016-08-14 15:13:34,109] DEBUG    FileServer Conn# 1 boot.zeronet.io [?] > Connecting...
[2016-08-14 15:13:34,204] DEBUG    Site:1CQTfY..6AXf Found 8 peers, new: 4
[2016-08-14 15:13:34,810] DEBUG    FileServer Removing Conn# 1 boot.zeronet.io [v2]...
[2016-08-14 15:13:34,865] DEBUG    Site:1Pz5E5..xGKG Announced types [] in mode startup to 7 trackers in 0.757s, errors: [], slow: []
[2016-08-14 15:13:34,866] DEBUG    Site:1Pz5E5..xGKG loadContent same json file, skipping
[2016-08-14 15:13:35,109] INFO     FileServer Checking port 15441 using portchecker.co...
[2016-08-14 15:13:35,690] INFO     FileServer [BAD :(] Port closed: Port 15441 is closed.
[2016-08-14 15:13:35,690] INFO     FileServer Trying to open port using UpnpPunch...
[2016-08-14 15:13:35,698] DEBUG    - Found local ips: ['192.168.1.12']
[2016-08-14 15:13:35,698] DEBUG    - Trying using local ip: 192.168.1.12
[2016-08-14 15:13:36,109] DEBUG    Site:1CQTfY..6AXf Need connections: 3, Current: 0, Total: 4
[2016-08-14 15:13:36,110] DEBUG    Site:1CQTfY..6AXf Small number of peers detected...query all of peers using pex
[2016-08-14 15:13:36,110] DEBUG    FileServer Conn# 2 108.13.70.202 [?] > Connecting...
[2016-08-14 15:13:36,264] INFO     Ui.UiServer --------------------------------------
[2016-08-14 15:13:36,264] INFO     Ui.UiServer Web interface: http://127.0.0.1:53903/
[2016-08-14 15:13:36,264] INFO     Ui.UiServer --------------------------------------
[2016-08-14 15:13:36,265] DEBUG    - Current RLIMIT_NOFILE: 1024, changing to 2048...
[2016-08-14 15:13:36,550] DEBUG    FileServer Conn# 2 108.13.70.202 [v2] > Crypt out connection using: tls-rsa (server side: False)...
[2016-08-14 15:13:37,230] DEBUG    FileServer Conn# 3 98.191.67.106 [?] > Connecting...
[2016-08-14 15:13:37,866] DEBUG    Site:1Pz5E5..xGKG Small number of peers detected...query all of peers using pex
[2016-08-14 15:13:37,866] DEBUG    Site:1Pz5E5..xGKG Queried pex from 0 peers got 0 new peers.
[2016-08-14 15:13:39,393] DEBUG    Site:1CQTfY..6AXf Announced types [] in mode startup to 7 trackers in 5.285s, errors: [], slow: ['5.22s http://torrent.gresille.org/announce']
[2016-08-14 15:13:39,396] DEBUG    Site:1CQTfY..6AXf Try to get listModifications from peers: [<Peer:108.13.70.202>, <Peer:41.96.72.123>, <Peer:196.210.77.239>, <Peer:178.63.104.217>, <Peer:41.96.146.236>] since: 1467308953.07
[2016-08-14 15:13:39,396] DEBUG    FileServer Conn# 4 41.96.72.123 [?] > Connecting...
[2016-08-14 15:13:39,397] DEBUG    FileServer Conn# 5 196.210.77.239 [?] > Connecting...
[2016-08-14 15:13:39,623] DEBUG    FileServer Conn# 6 178.63.104.217 [?] > Connecting...
[2016-08-14 15:13:39,681] DEBUG    FileServer 196.210.77.239 Connect error: error: [Errno 111] Connection refused in ConnectionServer.py line 139 > Connection.py line 95 > _socket2.py line 228
[2016-08-14 15:13:39,681] DEBUG    FileServer Removing Conn# 5 196.210.77.239 [?]...
[2016-08-14 15:13:39,697] DEBUG    FileServer Conn# 7 41.96.146.236 [?] > Connecting...
[2016-08-14 15:13:39,697] DEBUG    FileServer 178.63.104.217 Connect error: error: [Errno 111] Connection refused in ConnectionServer.py line 139 > Connection.py line 95 > _socket2.py line 228
[2016-08-14 15:13:39,697] DEBUG    FileServer Removing Conn# 6 178.63.104.217 [?]...
[2016-08-14 15:13:39,867] DEBUG    Site:1Pz5E5..xGKG Waiting for peers...
[2016-08-14 15:13:40,699] DEBUG    - UDP SSDP M-SEARCH send error using ip 192.168.1.12: timed out
[2016-08-14 15:13:40,699] DEBUG    - No IGD response
[2016-08-14 15:13:40,699] DEBUG    - Trying using local ip: 192.168.1.12
[2016-08-14 15:13:45,702] DEBUG    - UDP SSDP M-SEARCH send error using ip 192.168.1.12: timed out
[2016-08-14 15:13:45,702] DEBUG    - No IGD response
[2016-08-14 15:13:45,702] DEBUG    - Trying using local ip: 192.168.1.12
[2016-08-14 15:13:45,868] DEBUG    Site:1Pz5E5..xGKG Waiting for peers...
[2016-08-14 15:13:49,497] DEBUG    Site:1CQTfY..6AXf Queried listModifications from: [<Peer:108.13.70.202>]
[2016-08-14 15:13:49,508] DEBUG    Site:1CQTfY..6AXf Checked files in 0.01s... Found bad files: 0, Quick:True
[2016-08-14 15:13:49,509] DEBUG    Site:1CQTfY..6AXf Need connections: 3, Current: 1, Total: 10
[2016-08-14 15:13:50,704] DEBUG    - UDP SSDP M-SEARCH send error using ip 192.168.1.12: timed out
[2016-08-14 15:13:50,704] DEBUG    - No IGD response
[2016-08-14 15:13:50,704] INFO     FileServer Checking port 15441 using portchecker.co...
[2016-08-14 15:13:51,204] INFO     FileServer [BAD :(] Port closed: Port 15441 is closed.
[2016-08-14 15:13:51,204] INFO     FileServer Checking port 15441 using canyouseeme.org...
[2016-08-14 15:13:51,697] INFO     FileServer [BAD :(] Port closed: Error: I could not see your service on 62.101.36.14 on port (15441) Reason: Connection refused
[2016-08-14 15:13:51,698] INFO     FileServer Upnp mapping failed :( Please forward port 15441 on your router to your ipaddress
[2016-08-14 15:13:52,868] DEBUG    Site:1Pz5E5..xGKG Waiting for peers...
[2016-08-14 15:14:00,875] DEBUG    Site:1Pz5E5..xGKG Waiting for peers...
[2016-08-14 15:14:09,881] DEBUG    Site:1Pz5E5..xGKG Waiting for peers...
[2016-08-14 15:14:19,882] DEBUG    Site:1Pz5E5..xGKG Waiting for peers...
[2016-08-14 15:14:30,892] DEBUG    Site:1Pz5E5..xGKG Waiting for peers...
[2016-08-14 15:14:42,901] DEBUG    Site:1Pz5E5..xGKG Waiting for peers...
[2016-08-14 15:14:55,906] DEBUG    Site:1Pz5E5..xGKG Waiting for peers...
[2016-08-14 15:15:09,912] DEBUG    Site:1Pz5E5..xGKG Waiting for peers...
[2016-08-14 15:15:09,912] DEBUG    Site:1Pz5E5..xGKG Try to get listModifications from peers: [] since: 1470763650.11
[2016-08-14 15:15:10,012] DEBUG    Site:1Pz5E5..xGKG Queried listModifications from: []
[2016-08-14 15:15:10,013] DEBUG    Site:1Pz5E5..xGKG [MISSING] css/icheck/flat/Thumbs.db
[2016-08-14 15:15:10,023] DEBUG    Site:1Pz5E5..xGKG Checked files in 0.01s... Found bad files: 1, Quick:True
[2016-08-14 15:15:10,024] DEBUG    Site:1Pz5E5..xGKG loadContent same json file, skipping
[2016-08-14 15:15:10,024] DEBUG    Site:1Pz5E5..xGKG Bad files: {u'css/icheck/flat/Thumbs.db': 1}
[2016-08-14 15:15:10,024] DEBUG    Site:1Pz5E5..xGKG Start downloading, bad_files: {'content.json': 1, u'css/icheck/flat/Thumbs.db': 1}, check_size: False, blind_includes: False
[2016-08-14 15:15:10,024] DEBUG    WorkerManager:1Pz5E5..xGKG New task: content.json, peer lock: None, priority: 0, optional_hash_id: None, tasks: 1
[2016-08-14 15:15:10,025] DEBUG    FileServer Conn# 8 boot.zeronet.io [?] > Connecting...
[2016-08-14 15:15:10,241] DEBUG    Site:1Pz5E5..xGKG Http tracker http://tracker.aletorrenty.pl:2710/announce?uploaded=0&downloaded=0&numwant=30&compact=1&event=started&peer_id=-ZN001a-JDo3cCtLIgQL&port=0&info_hash=%98%86%D4xLx%9A%AB%92y%A1%B7%D0%B7uR%16%E4%7B%07&left=0 error: [Errno 104] Connection reset by peer
[2016-08-14 15:15:10,825] DEBUG    Site:1Pz5E5..xGKG Announced types [] in mode start to 6 trackers in 0.800s, errors: ['http://tracker.aletorrenty.pl:2710/announce'], slow: []
[2016-08-14 15:15:13,827] DEBUG    Site:1Pz5E5..xGKG Small number of peers detected...query all of peers using pex
[2016-08-14 15:15:13,827] DEBUG    Site:1Pz5E5..xGKG Queried pex from 0 peers got 0 new peers.
[2016-08-14 15:15:19,079] DEBUG    WorkerManager:1Pz5E5..xGKG Task taking more than 15+0 secs, workers: 0 find more peers: content.json
[2016-08-14 15:15:34,053] DEBUG    FileServer Conn# 3 98.191.67.106 [?] > [Cleanup] Connect timeout: 116.822834969
[2016-08-14 15:15:34,053] DEBUG    FileServer Removing Conn# 3 98.191.67.106 [?]...
[2016-08-14 15:15:34,053] DEBUG    FileServer Conn# 4 41.96.72.123 [?] > [Cleanup] Connect timeout: 114.657162905
[2016-08-14 15:15:34,054] DEBUG    FileServer Removing Conn# 4 41.96.72.123 [?]...
[2016-08-14 15:15:34,054] DEBUG    FileServer Conn# 7 41.96.146.236 [?] > [Cleanup] Connect timeout: 114.356825113
[2016-08-14 15:15:34,054] DEBUG    FileServer Removing Conn# 7 41.96.146.236 [?]...
[2016-08-14 15:15:34,054] DEBUG    FileServer Conn# 8 boot.zeronet.io [v2] > [Cleanup] Tracker connection: 23.2854990959
[2016-08-14 15:15:34,054] DEBUG    FileServer Removing Conn# 8 boot.zeronet.io [v2]...
[2016-08-14 15:15:34,055] DEBUG    FileServer 98.191.67.106 Connect error: error: [Errno 9] File descriptor was closed in another greenlet in ConnectionServer.py line 139 > Connection.py line 95 > _socket2.py line 233 > _socket2.py line 179 > hub.py line 627 > hub.py line 875 > hub.py line 606
[2016-08-14 15:15:34,055] DEBUG    FileServer Conn# 9 50.156.248.189 [?] > Connecting...
[2016-08-14 15:15:34,056] DEBUG    FileServer 41.96.72.123 Connect error: error: [Errno 9] File descriptor was closed in another greenlet in ConnectionServer.py line 139 > Connection.py line 95 > _socket2.py line 233 > _socket2.py line 179 > hub.py line 627 > hub.py line 875 > hub.py line 606
[2016-08-14 15:15:34,056] DEBUG    FileServer 41.96.146.236 Connect error: error: [Errno 9] File descriptor was closed in another greenlet in ConnectionServer.py line 139 > Connection.py line 95 > _socket2.py line 233 > _socket2.py line 179 > hub.py line 627 > hub.py line 875 > hub.py line 606
[2016-08-14 15:15:34,080] DEBUG    WorkerManager:1Pz5E5..xGKG Task taking more than 15+0 secs, workers: 0 find more peers: content.json
[2016-08-14 15:15:49,094] DEBUG    WorkerManager:1Pz5E5..xGKG Task taking more than 15+0 secs, workers: 0 find more peers: content.json
[2016-08-14 15:15:49,095] DEBUG    FileServer Conn#10 boot.zeronet.io [?] > Connecting...
[2016-08-14 15:15:49,849] DEBUG    Site:1Pz5E5..xGKG Announced types [] in mode more to 1 trackers in 0.754s, errors: [], slow: []
[2016-08-14 15:15:52,851] DEBUG    Site:1Pz5E5..xGKG Small number of peers detected...query all of peers using pex
[2016-08-14 15:15:52,852] DEBUG    Site:1Pz5E5..xGKG Queried pex from 0 peers got 0 new peers.
[2016-08-14 15:16:04,850] DEBUG    WorkerManager:1Pz5E5..xGKG Task taking more than 15+0 secs, workers: 0 find more peers: content.json
[2016-08-14 15:16:10,343] DEBUG    Site:1CQTfY..6AXf Announced types [] in mode update to 1 trackers in 0.224s, errors: [], slow: []
[2016-08-14 15:16:10,343] DEBUG    Site:1CQTfY..6AXf Need connections: 3, Current: 1, Total: 10
[2016-08-14 15:16:19,850] DEBUG    WorkerManager:1Pz5E5..xGKG Timeout, Cleanup task: {'optional_hash_id': None, 'site': <Site 1Pz5E5..xGKG>, 'done': False, 'size': 0, 'inner_path': 'content.json', 'peers': None, 'time_started': None, 'time_action': None, 'priority': 0, 'failed': [], 'workers_num': 0, 'time_added': 1471180510.024864, 'evt': <gevent.event.AsyncResult object at 0x7fc82860e6d0>}
[2016-08-14 15:16:19,850] DEBUG    Site:1Pz5E5..xGKG Can't update content.json
[2016-08-14 15:16:19,851] DEBUG    Site:1Pz5E5..xGKG Download content.json failed, check_modifications: False
[2016-08-14 15:16:19,851] DEBUG    WorkerManager:1Pz5E5..xGKG New task: content.json, peer lock: None, priority: 0, optional_hash_id: None, tasks: 1
[2016-08-14 15:16:19,851] DEBUG    WorkerManager:1Pz5E5..xGKG New task: css/icheck/flat/Thumbs.db, peer lock: None, priority: 0, optional_hash_id: None, tasks: 2
[2016-08-14 15:16:34,061] DEBUG    FileServer Conn# 9 50.156.248.189 [?] > [Cleanup] Connect timeout: 60.005202055
[2016-08-14 15:16:34,061] DEBUG    FileServer Removing Conn# 9 50.156.248.189 [?]...
[2016-08-14 15:16:34,061] DEBUG    FileServer 50.156.248.189 Connect error: error: [Errno 9] File descriptor was closed in another greenlet in ConnectionServer.py line 139 > Connection.py line 95 > _socket2.py line 233 > _socket2.py line 179 > hub.py line 627 > hub.py line 875 > hub.py line 606
[2016-08-14 15:16:34,061] DEBUG    FileServer Conn#11 41.96.13.25  [?] > Connecting...
[2016-08-14 15:16:34,851] DEBUG    WorkerManager:1Pz5E5..xGKG Task taking more than 15+0 secs, workers: 0 find more peers: content.json
[2016-08-14 15:16:34,976] DEBUG    Site:1Pz5E5..xGKG Announced types [] in mode more to 1 trackers in 0.125s, errors: [], slow: []
[2016-08-14 15:16:37,979] DEBUG    Site:1Pz5E5..xGKG Small number of peers detected...query all of peers using pex
[2016-08-14 15:16:37,979] DEBUG    Site:1Pz5E5..xGKG Queried pex from 0 peers got 0 new peers.
[2016-08-14 15:16:49,977] DEBUG    WorkerManager:1Pz5E5..xGKG Task taking more than 15+0 secs, workers: 0 find more peers: content.json
[2016-08-14 15:17:04,978] DEBUG    WorkerManager:1Pz5E5..xGKG Task taking more than 15+0 secs, workers: 0 find more peers: content.json
[2016-08-14 15:17:14,078] ERROR    Site:1Pz5E5..xGKG Announce to 0 trackers in 9.100s, failed
[2016-08-14 15:17:17,081] DEBUG    Site:1Pz5E5..xGKG Small number of peers detected...query all of peers using pex
[2016-08-14 15:17:17,081] DEBUG    Site:1Pz5E5..xGKG Queried pex from 0 peers got 0 new peers.
[2016-08-14 15:17:29,086] DEBUG    WorkerManager:1Pz5E5..xGKG Timeout, Cleanup task: {'optional_hash_id': None, 'site': <Site 1Pz5E5..xGKG>, 'done': False, 'size': 0, 'inner_path': 'content.json', 'peers': None, 'time_started': None, 'time_action': None, 'priority': 0, 'failed': [], 'workers_num': 0, 'time_added': 1471180579.85134, 'evt': <gevent.event.AsyncResult object at 0x7fc8283c5f10>}
[2016-08-14 15:17:29,086] DEBUG    Site:1Pz5E5..xGKG Can't update content.json
[2016-08-14 15:17:29,086] DEBUG    WorkerManager:1Pz5E5..xGKG Timeout, Cleanup task: {'optional_hash_id': None, 'site': <Site 1Pz5E5..xGKG>, 'done': False, 'size': 19968, 'inner_path': u'css/icheck/flat/Thumbs.db', 'peers': None, 'time_started': None, 'time_action': None, 'priority': 0, 'failed': [], 'workers_num': 0, 'time_added': 1471180579.851568, 'evt': <gevent.event.AsyncResult object at 0x7fc8283c5d10>}
[2016-08-14 15:17:34,065] DEBUG    FileServer Conn#10 boot.zeronet.io [v2] > [Cleanup] Tracker connection: 104.269278049
[2016-08-14 15:17:34,066] DEBUG    FileServer Removing Conn#10 boot.zeronet.io [v2]...
[2016-08-14 15:17:34,066] DEBUG    FileServer Conn#11 41.96.13.25  [?] > [Cleanup] Connect timeout: 60.0045249462
[2016-08-14 15:17:34,066] DEBUG    FileServer Removing Conn#11 41.96.13.25  [?]...
[2016-08-14 15:17:34,066] DEBUG    FileServer 41.96.13.25 Connect error: error: [Errno 9] File descriptor was closed in another greenlet in ConnectionServer.py line 139 > Connection.py line 95 > _socket2.py line 233 > _socket2.py line 179 > hub.py line 627 > hub.py line 875 > hub.py line 606
[2016-08-14 15:17:34,066] DEBUG    Site:1CQTfY..6AXf Queried pex from 1 peers got 6 new peers.
[2016-08-14 15:18:42,511] DEBUG    Site:1Pz5E5..xGKG Announced types [] in mode update to 1 trackers in 0.158s, errors: [], slow: []
[2016-08-14 15:18:44,615] DEBUG    Site:1CQTfY..6AXf Http tracker http://tracker.aletorrenty.pl:2710/announce?uploaded=0&downloaded=0&numwant=30&compact=1&event=started&peer_id=-ZN001a-JDo3cCtLIgQL&port=0&info_hash=m%07S%40%9C%1A%C7F%2F%2A%02%F5%C7%DD%D7%16%93%21%E8.&left=0 error: [Errno 104] Connection reset by peer
[2016-08-14 15:18:44,664] DEBUG    Site:1CQTfY..6AXf Need connections: 3, Current: 1, Total: 10
[2016-08-14 15:19:34,067] INFO     FileServer Internet offline
[2016-08-14 15:21:16,761] DEBUG    Site:1Pz5E5..xGKG Http tracker http://tracker.aletorrenty.pl:2710/announce?uploaded=0&downloaded=0&numwant=30&compact=1&event=started&peer_id=-ZN001a-JDo3cCtLIgQL&port=0&info_hash=%98%86%D4xLx%9A%AB%92y%A1%B7%D0%B7uR%16%E4%7B%07&left=0 error: [Errno 104] Connection reset by peer
[2016-08-14 15:21:19,193] DEBUG    Site:1CQTfY..6AXf Announced types [] in mode update to 1 trackers in 0.385s, errors: [], slow: []
[2016-08-14 15:21:19,193] DEBUG    Site:1CQTfY..6AXf Need connections: 3, Current: 1, Total: 10
[2016-08-14 15:21:42,151] ERROR    - Unhandled exception
None
[2016-08-14 15:21:42,152] DEBUG    Ui.UiServer Stopping...
[2016-08-14 15:21:42,152] INFO     gshift Stopping gshift...
[2016-08-14 15:21:42,152] ERROR    gshift Error stopping gshift: [Errno 3] No such process
[2016-08-14 15:21:42,153] DEBUG    Ui.UiServer Socket closed: 0
[2016-08-14 15:21:42,153] DEBUG    FileServer Stopped.
[2016-08-14 15:21:42,406] DEBUG    Ui.UiServer Stopped.
[2016-08-14 15:21:42,407] INFO     gshift Stopping gshift...
[2016-08-14 15:21:42,407] ERROR    gshift Error stopping gshift: [Errno 3] No such process
